name: Trigger Job 1
on:
  workflow_call:
    inputs:
      job1_input:
        description: Input for Job 1
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Job 1
        run: |
          echo "Running Job 1 with input: ${{ inputs.job1_input }}"
          # Add your job 1 logic here
          echo "Job 1 completed successfully."