name: Trigger Job 1
on:
  workflow_call:
    inputs:
      job2_input:
        description: Input for Job 2
        required: true
        type: string

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Job 2
        run: |
          echo "Running Job 2 with input: ${{ inputs.job2_input }}"
          # Add your job 2 logic here
          echo "Job 2 completed successfully."