name: Trigger Job 2
description: This action triggers Job 1 in the workflow.
inputs:
  job1_input:
    description: Input for Job 1
    required: true
    default: 'default_value'
jobs:
  steps: 
    - name: Trigger Job 2
      run: |
        echo "Running Job 2 with input: ${{ inputs.job1_input }}"
        # Add your job 2 logic here
        echo "Job 2 completed successfully."