name: Manual Swap Azure Web App Slot
on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'myappxxx'
  RESOURCE_GROUP: '1-bd26b9ec-playground-sandbox'
  SLOT_NAME: 'v2'  # Replace with your slot name if needed
jobs:
  Manual-Swap:
    runs-on: ubuntu-latest
    environment: swap-gate 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: authenticate with Azure
      run: | 
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
    - name: Please wait 
      run: echo "Swapping Slots... Please Wait...!!!"  # Wait for the settings to be applied before swapping slots
    - name: Swap Azure Web App Slots
      uses: ./.github/actions/swap-slot
      with:
        AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
        RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
        SOURCE_SLOT_NAME: ${{ env.SLOT_NAME }}
        TARGET_SLOT_NAME: 'production'