name: Reusable Workflow
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Trigger Job 1
        uses: .github/actions/job1.yaml@main
        with:
          job1_input: 'input_value_for_job1'  
  job2:
    runs-on: ubuntu-latest
    needs: job1 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Trigger Job 2
        uses: .github/actions/job2.yaml@main
        with:
          job2_input: 'input_value_for_job2'
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Final Job
        run: |
          echo "Running final job after Job 1 and Job 2"