name: Reusable Workflow
on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
  calling_job1:
    uses: ./.github/workflows/job1.yaml
    with:
      job1_input: 'input_value_for_job1'  

  calling_job2:
    # runs-on: ubuntu-latest
    needs: calling_job1
    uses: ./.github/workflows/job2.yaml
    with:
      job2_input: 'input_value_for_job2'  

  job3:
    runs-on: ubuntu-latest
    needs: [calling_job1, calling_job2]
    steps:
      - name: Final Job
        run: |
          echo "Running final job after Job 1 and Job 2"