name: Configure Azure Web App Settings

on:
  push:
    branches: [ main, 'feature/*' ]
    # paths: [ 'appsettings.json' ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'myappxxx'
  RESOURCE_GROUP: '1-4ba8b344-playground-sandbox'
  SLOT_NAME: 'staging'  # Replace with your slot name if needed

jobs:
  configure-settings:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: authenticate with Azure
      run: | 
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Parse JSON settings
      id: parse-settings
      run: |
        # Read JSON file and format for Azure CLI
        SETTINGS_JSON=$(jq -c '.settings[] | "\(.name)=\(.value)"' settings/appsettings.json | tr '\n' ' ')
        echo "settings_json=${SETTINGS_JSON//\"/}" >> $GITHUB_OUTPUT

    - name: Apply settings to Web App
      run: |
        az webapp config appsettings set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --slot ${{ env.SLOT_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --settings ${{ steps.parse-settings.outputs.settings_json }}

    - name: Apply slot-specific settings
      run: |
        # Filter slot-specific settings and apply
        SLOT_SETTINGS_COUNT=$(jq '[.settings[] | select(.slotSetting == true)] | length' settings/appsettings.json)
        
        if [ "$SLOT_SETTINGS_COUNT" -eq 0 ]; then
          echo "No slot-specific settings to apply"
          exit 0
        fi

        # Process settings with proper JSON handling
        jq -r '.settings[] | select(.slotSetting == true) | 
              "\(.name)=\(.value)"' settings/appsettings.json | \
        while IFS= read -r setting; do
          echo "Applying setting: ${setting%%=*}"
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --slot ${{ env.SLOT_NAME }} \
            --slot-settings "$setting" \
        done

    - name: Verify settings
      run: |
        echo "Current settings:"
        az webapp config appsettings list \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --output table